server:
  port: 8082


spring:
     project:
         name: huyapassport
     application:
         name: eureka-admin--starter-server

logging:
  level:
    com:
      itopener: DEBUG
    org:
      springframework: INFO
