server:
  port: 11111

spring:
     project:
         name: eureka
     application:
         name: eureka-admin--starter-server

eureka:
  client:
    refresh:
      interval: 1

eureka.envs:
  - name: test
    chineseName: 测试
    url: yourUrl
  - name: prod
    chineseName: 生产
    url: yourUrl
