eureka.clusters:
  - name: zhixu
    chineseName: 秩序
    serviceUrl: https://test1-zx-eureka.huya.com/eureka/
    selfadminUrl: https://test1-zx-eureka.huya.com
  - name: passport
    chineseName: 账号
    serviceUrl: https://eureka-udb-test.huya.info/eureka/
    selfadminUrl: https://eureka-udb-test.huya.info
  - name: passportsg
    chineseName: 账号海外
    serviceUrl: https://udb-inner-ek2-hw-test.huya.info/eureka/
    selfadminUrl: https://udb-inner-ek2-hw-test.huya.info
  - name: zhifu
    chineseName: 支付
    serviceUrl: http://paygate-eureka-test.local.pay.hy:8101/eureka/
    selfadminUrl: http://paygate-eureka-test.local.pay.hy:8101
  - name: zhifusg
    chineseName: 支付海外
    serviceUrl: http://paygate-sg-eureka-test.local.pay.hy:8101/eureka/
    selfadminUrl: http://paygate-sg-eureka-test.local.pay.hy:8101
