eureka.clusters:
  - name: zhixu
    chineseName: 秩序
    serviceUrl: your eureka url
    selfadminUrl: eureka self admin url
  - name: passport
    chineseName: 账号
    serviceUrl: your eureka url
    selfadminUrl: eureka self admin url

