eureka.clusters:
  - name: zhixu
    chineseName: 秩序
    serviceUrl: https://test1-zx-eureka.huya.com/eureka/
    selfadminUrl: https://test1-zx-eureka.huya.com
  - name: passport
    chineseName: 账号
    serviceUrl: https://eureka-udb-test.huya.info/eureka/
    selfadminUrl: https://eureka-udb-test.huya.info

