server:
  port: 8010

eureka:
  server: 
    eviction-interval-timer-in-ms: 30000
  client:
    register-with-eureka: false
    fetch-registry: true
    filterOnlyUpInstances: false
    serviceUrl:
       defaultZone: http://inner-ek1.huyaudb.com:9500/eureka/

spring:
     project:
         name: huyapassport
     application:
         name: eureka-admin-serv

logging:
  level:
    com:
      itopener: DEBUG
    org:
      springframework: INFO
